/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordIndexRouteImport } from './routes/record/index'
import { Route as RecordModeRouteImport } from './routes/record/$mode'
import { Route as RecordingIdRouteImport } from './routes/recording/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIndexRoute = RecordIndexRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordModeRoute = RecordModeRouteImport.update({
  id: '/record/$mode',
  path: '/record/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingIdRoute = RecordingIdRouteImport.update({
  id: '/recording/$id',
  path: '/recording/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/record/$mode': typeof RecordModeRoute
  '/recording/$id': typeof RecordingIdRoute
  '/record/': typeof RecordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/record/$mode': typeof RecordModeRoute
  '/recording/$id': typeof RecordingIdRoute
  '/record': typeof RecordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/record/$mode': typeof RecordModeRoute
  '/recording/$id': typeof RecordingIdRoute
  '/record/': typeof RecordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/insights'
    | '/settings'
    | '/record/$mode'
    | '/recording/$id'
    | '/record/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/insights'
    | '/settings'
    | '/record/$mode'
    | '/recording/$id'
    | '/record'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/insights'
    | '/settings'
    | '/record/$mode'
    | '/recording/$id'
    | '/record/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  InsightsRoute: typeof InsightsRoute
  SettingsRoute: typeof SettingsRoute
  RecordModeRoute: typeof RecordModeRoute
  RecordingIdRoute: typeof RecordingIdRoute
  RecordIndexRoute: typeof RecordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record/'
      preLoaderRoute: typeof RecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/$mode': {
      id: '/record/$mode'
      path: '/record/$mode'
      fullPath: '/record/$mode'
      preLoaderRoute: typeof RecordModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording/$id': {
      id: '/recording/$id'
      path: '/recording/$id'
      fullPath: '/recording/$id'
      preLoaderRoute: typeof RecordingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  InsightsRoute: InsightsRoute,
  SettingsRoute: SettingsRoute,
  RecordModeRoute: RecordModeRoute,
  RecordingIdRoute: RecordingIdRoute,
  RecordIndexRoute: RecordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
